// src/design-system/components/Input/Input.tsx
import type { InputHTMLAttributes } from "react";

export interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export function Input({ label, error, className = "", ...props }: InputProps) {
  const ring = error
    ? "border-error focus:ring-[rgba(239,68,68,.18)]"
    : "border-neutral-200 focus:border-gold-500 focus:ring-[rgba(245,158,11,.22)]";

  return (
    <label className="flex w-full flex-col gap-1.5">
      {label && (
        <span className="text-sm font-medium text-neutral-700">{label}</span>
      )}
      <input
        className={`w-full rounded-[var(--radius-md)] border bg-white px-3.5 py-3 text-[15px] text-neutral-900 outline-none transition focus:ring-2 disabled:cursor-not-allowed disabled:bg-neutral-50 disabled:text-neutral-400 ${ring} ${className}`}
        {...props}
      />
      {error && <span className="text-sm text-error">{error}</span>}
    </label>
  );
}

// apps/web/src/design-system/components/Input/Input.vue
<script setup lang="ts">
defineProps<{
  modelValue?: string;
  type?: string;
  placeholder?: string;
  label?: string;
  error?: string;
  disabled?: boolean;
}>();

defineEmits<{ 'update:modelValue': [value: string] }>();
</script>

<template>
  <div class="flex flex-col gap-1">
    <label v-if="label" class="text-sm font-medium text-neutral-700">{{ label }}</label>
    <input
      :type="type ?? 'text'"
      :value="modelValue"
      :placeholder="placeholder"
      :disabled="disabled"
      :class="[
        'w-full rounded-lg border px-3 py-2 text-neutral-900 placeholder-neutral-400 transition-colors focus:outline-none focus:ring-2',
        error ? 'border-red-400 focus:ring-red-300' : 'border-neutral-300 focus:border-gold-400 focus:ring-gold-200',
        disabled ? 'opacity-50 cursor-not-allowed bg-neutral-50' : 'bg-white',
      ]"
      @input="$emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
    <p v-if="error" class="text-sm text-red-600">{{ error }}</p>
  </div>
</template>
