// apps/web/src/features/auth/components/LoginForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useI18n } from 'vue-i18n';
import { useAuth } from '../composables/useAuth';
import { Button, Input } from '@/design-system';

const { t } = useI18n();
const { login, loading, error } = useAuth();

const email = ref('');
const password = ref('');
</script>

<template>
  <form class="flex flex-col gap-4" @submit.prevent="login(email, password)">
    <Input v-model="email" type="email" :label="t('auth.email')" :placeholder="t('auth.email')" />
    <Input v-model="password" type="password" :label="t('auth.password')" :placeholder="t('auth.password')" />
    <p v-if="error" class="text-sm text-red-600">{{ t('auth.invalid_credentials') }}</p>
    <Button type="submit" :loading="loading" class="w-full">{{ t('auth.submit') }}</Button>
  </form>
</template>

// src/features/auth/components/LoginForm.tsx
"use client";

import { useActionState } from "react";
import { useTranslations } from "next-intl";
import { Button, Input } from "@/design-system";
import { loginAction, type AuthState } from "../actions";

const initial: AuthState = {};

export function LoginForm() {
  const t = useTranslations("auth");
  const [state, action, pending] = useActionState(loginAction, initial);

  return (
    <form action={action} className="flex flex-col gap-4">
      <Input
        name="email"
        type="email"
        label={t("email")}
        placeholder={t("emailPlaceholder")}
        autoComplete="email"
        autoFocus
        required
      />
      <Input
        name="password"
        type="password"
        label={t("password")}
        autoComplete="current-password"
        required
      />
      {state.error && <p className="text-sm text-error">{state.error}</p>}
      <Button type="submit" disabled={pending} className="mt-2 w-full">
        {pending ? t("signingIn") : t("signIn")}
      </Button>
    </form>
  );
}
