// apps/web/src/features/study/components/FlipCard.vue
<script setup lang="ts">
defineProps<{ flipped: boolean }>();
</script>

<template>
  <div class="flip relative min-h-60">
    <div class="flip-inner" :class="{ flipped }">
      <div class="flip-face"><slot name="front" /></div>
      <div class="flip-face flip-back"><slot name="back" /></div>
    </div>
  </div>
</template>

<style scoped>
.flip {
  perspective: 1200px;
}
.flip-inner {
  position: absolute;
  inset: 0;
  transform-style: preserve-3d;
  transition: transform 0.6s cubic-bezier(0.4, 0, 0.2, 1);
}
.flip-inner.flipped {
  transform: rotateY(180deg);
}
.flip-face {
  position: absolute;
  inset: 0;
  backface-visibility: hidden;
  -webkit-backface-visibility: hidden;
}
.flip-back {
  transform: rotateY(180deg);
}
@media (prefers-reduced-motion: reduce) {
  .flip-inner { transition: none; }
}
</style>

// src/features/review/components/FlipCard.tsx
import type { ReactNode } from "react";

const FACE =
  "absolute inset-0 flex flex-col justify-center overflow-auto rounded-[var(--radius-lg)] p-8 [backface-visibility:hidden]";

export function FlipCard({
  flipped,
  front,
  back,
}: {
  flipped: boolean;
  front: ReactNode;
  back: ReactNode;
}) {
  return (
    <div className="[perspective:1200px]">
      <div
        className={`relative min-h-64 w-full transition-transform duration-500 ease-[cubic-bezier(.4,0,.2,1)] [transform-style:preserve-3d] ${
          flipped ? "[transform:rotateY(180deg)]" : ""
        }`}
      >
        <div
          className={`${FACE} border border-line bg-surface shadow-[var(--shadow-sm)]`}
        >
          {front}
        </div>
        <div
          className={`${FACE} bg-neutral-900 shadow-[var(--shadow-md)] [transform:rotateY(180deg)]`}
        >
          {back}
        </div>
      </div>
    </div>
  );
}
