// apps/web/src/design-system/components/Button/Button.vue
<script setup lang="ts">
defineProps<{
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
  disabled?: boolean;
}>();

defineEmits<{ click: [] }>();
</script>

<template>
  <button
    :disabled="disabled || loading"
    :class="[
      'inline-flex items-center justify-center font-medium rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2',
      size === 'sm' ? 'px-3 py-1.5 text-sm' : size === 'lg' ? 'px-6 py-3 text-lg' : 'px-4 py-2 text-base',
      variant === 'secondary' ? 'bg-neutral-100 text-neutral-800 hover:bg-neutral-200 focus:ring-neutral-400' :
      variant === 'danger'    ? 'bg-red-600 text-white hover:bg-red-700 focus:ring-red-500' :
      variant === 'ghost'     ? 'bg-transparent text-gold-700 hover:bg-gold-50 focus:ring-gold-500' :
                                'bg-gold-500 text-neutral-900 hover:bg-gold-600 focus:ring-gold-400',
      (disabled || loading) ? 'opacity-50 cursor-not-allowed' : '',
    ]"
    @click="$emit('click')"
  >
    <span v-if="loading" class="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-neutral-900 border-t-transparent" />
    <slot />
  </button>
</template>

// src/design-system/components/Button/Button.tsx
import type { ButtonHTMLAttributes } from "react";

type Variant = "primary" | "secondary" | "ghost";
type Size = "sm" | "md";

const base =
  "inline-flex items-center justify-center gap-2 font-sans font-semibold rounded-[var(--radius-md)] transition-all duration-150 focus:outline-none focus-visible:ring-2 focus-visible:ring-gold-400 disabled:cursor-not-allowed";

const variants: Record<Variant, string> = {
  primary:
    "bg-gold-600 text-white shadow-[0_2px_8px_rgba(217,119,6,.30)] hover:bg-gold-700 hover:-translate-y-px active:translate-y-0 disabled:bg-neutral-100 disabled:text-neutral-400 disabled:shadow-none",
  secondary:
    "bg-white text-neutral-700 border border-neutral-200 hover:bg-neutral-50 active:bg-neutral-100 disabled:text-neutral-300",
  ghost:
    "bg-transparent text-indigo-600 hover:bg-indigo-50 disabled:text-neutral-300",
};

const sizes: Record<Size, string> = {
  sm: "text-sm px-4 py-2",
  md: "text-[15px] px-[22px] py-3",
};

export interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant;
  size?: Size;
}

export function Button({
  variant = "primary",
  size = "md",
  className = "",
  ...props
}: ButtonProps) {
  return (
    <button
      className={`${base} ${variants[variant]} ${sizes[size]} ${className}`}
      {...props}
    />
  );
}
